# import pdb
#
# pdb.set_trace()

# import pydevd_pycharm
#
# pydevd_pycharm.settrace(
#     "127.0.0.1", port=60293, stdoutToServer=True, stderrToServer=True
# )

from gvas import GVASFile
from gvas import GameVersion, CompressionType
import json
import dataclasses
import uuid
from gvas.gvas_types import Guid


# ============================================
class EnhancedJSONEncoder(json.JSONEncoder):
    def default(self, o):
        if dataclasses.is_dataclass(o):
            return dataclasses.asdict(o)
        elif isinstance(o, uuid):
            print(f"uuid: {o}")
            return str(o)
        elif isinstance(o, Guid):
            print(f"Guid: {o}")
            return str(o)
        return super().default(o)


# This code was generated by interacting with the Cursor IDE using Claude Sonnet 3.5 and 3.7.
# This does not yet include ALL the properties, like MAP and delegate and (others). But returns were diminishing so we need to standardize format and implementation before adding the others.

# TODO: add in property implementations for delegate, field_path, map, object, text, unknown

# first things first. We need to exercise reading the GVAS file header

example_gvas = "Islands of Insight Example.sav"
print(f"Loading {example_gvas}")
# Open and read a save file
gvas_file = None
with open(example_gvas, "rb") as f:
    print(f"loading file with target: {GameVersion.DEFAULT}")
    gvas_file = GVASFile.read(f, GameVersion.DEFAULT, CompressionType)

# dump for debug
with open("ugly_debug.txt", "w") as f:
    f.write(str(gvas_file))
    # f.write(json.dumps(gvas_file, cls=EnhancedJSONEncoder))

# dump binary to work toward idempotence for read, write, rinse and repeat
with open("idempotent.sav", "wb") as f:
    gvas_file.write(f, GameVersion.DEFAULT)
