# import pdb
#
# pdb.set_trace()

# import pydevd_pycharm
#
# pydevd_pycharm.settrace(
#     "127.0.0.1", port=60293, stdoutToServer=True, stderrToServer=True
# )

from gvas import GVASFile, DeserializeError
from gvas import GameVersion, CompressionType
import json
import dataclasses
import uuid
from gvas.gvas_types import Guid


# ============================================
class EnhancedJSONEncoder(json.JSONEncoder):
    def default(self, o):
        if dataclasses.is_dataclass(o):
            return dataclasses.asdict(o)
        elif isinstance(o, uuid):
            print(f"uuid: {o}")
            return str(o)
        elif isinstance(o, Guid):
            print(f"Guid: {o}")
            return str(o)
        return super().default(o)


# This code was generated by interacting with the Cursor IDE using Claude Sonnet 3.5 and 3.7.
# This does not yet include ALL the properties, like MAP and delegate and (others). But returns were diminishing so we need to standardize format and implementation before adding the others.

# TODO: add in property implementations for delegate, field_path, map, object, text, unknown

# first things first. We need to exercise reading the GVAS file header

test_file_list = ["Islands of Insight Example.sav"]

# The Rust package engineer created a plethora of tests. Let's cycle through them.
import pathlib

test_directory = pathlib.Path("./resources/test")
test_file_list = [
    filepath for filepath in test_directory.glob("*.sav") if filepath.is_file()
]
# test_file_list = ["Islands of Insight Example.sav"]  # working!
# test_file_list = ["resources/test/component8.sav"]  # Working!
# test_file_list = ["resources/test/Options.sav"]  # Working!
# test_file_list = ["resources/test/Profile_0.sav"]  # Working!

test_file_list = ["resources/test/vector2d.sav"]  # Working!
test_file_list = ["resources/test/Delegate.sav"]  # Working!
test_file_list = ["resources/test/enum_array.sav"]  # Working!

# always a quick retest
# test_file_list = ["Islands of Insight Example.sav"]  # working!

# this one has complex stuff in it; more challenging!
# test_file_list = ["resources/test/package_version_524.sav"]

print(test_file_list)

for test_file in test_file_list:
    print(f"Loading {test_file}")
    # Open and read a save file
    gvas_file = None
    with open(test_file, "rb") as f:
        print(f"loading file with target: {GameVersion.DEFAULT}")
        gvas_file = GVASFile.read(f, GameVersion.DEFAULT, CompressionType.NONE)
        # try:
        #     gvas_file = GVASFile.read(f, GameVersion.DEFAULT, CompressionType.NONE)
        # except Exception as e:
        #     print(f"Failed to load {test_file}: {e}")
        #     continue

    # dump for debug
    # with open("ugly_debug.txt", "w") as f:
    #     f.write(str(gvas_file))
    #     # f.write(json.dumps(gvas_file, cls=EnhancedJSONEncoder))

    # dump binary to work toward idempotence for read, write, rinse and repeat
    output_file = f"{test_file}.idempotent"
    print(f"Writing {output_file}")
    with open(output_file, "wb") as f:
        gvas_file.write(f, GameVersion.DEFAULT)
